package com.neutrinos.manulife;

/**
 * This class was automatically generated by the data modeler tool.
 */
 
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import org.json.JSONObject;

public class NB_TOKEN_GENERATOR implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public NB_TOKEN_GENERATOR() {
    }

public static String getToken(String tokenName) {

		String inClientId = System.getenv("CM_IN_CLIENT_ID");
		String inClientSecret = System.getenv("CM_IN_CLIENT_SECRET");

		String cmClientId = System.getenv("CM_CLIENT_ID");
		String cmClientSecret = System.getenv("CM_CLIENT_SECRET");

		String tokenUrl = System.getenv("IDS_BASE_URL") + "token";

		String cmUrlParameters  = "client_secret="+cmClientSecret+"&client_id="+cmClientId+"&grant_type=client_credentials";
		String inUrlParameters  = "client_secret="+inClientSecret+"&client_id="+inClientId+"&grant_type=client_credentials";
		
		String accessToken="";
		String urlParameters="";
		try {
			if(tokenName.equals("cmToken")) {
				urlParameters = cmUrlParameters;
			} else {
				urlParameters = inUrlParameters;
			}			
	        StringBuilder result = new StringBuilder();
	        URL url = new URL(tokenUrl);
	        HttpURLConnection conn = (HttpURLConnection) url.openConnection();
	        conn.setRequestMethod("GET");
	        conn.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
	        conn.setRequestProperty("Content-Length", Integer.toString(urlParameters.getBytes().length));

	        conn.setUseCaches(false);
	        conn.setDoOutput(true);


	        DataOutputStream wr = new DataOutputStream (
	            conn.getOutputStream());
	            wr.writeBytes(urlParameters);
	            wr.close();

	            BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()));
	            String line;
	            while ((line = rd.readLine()) != null) {
	            	System.out.println(line);
	                result.append(line);
	            }
	            rd.close();
                accessToken = result.toString();
	           //String tokenResponse= result.toString();
	           //System.out.println("token response"+tokenResponse);
	           // JSONObject obje = new JSONObject(tokenResponse);
	           // accessToken=(String) obje.get("access_token");
	           // System.out.println("access_token"+obje.get("access_token"));
	        }
	        catch (Exception e) {
	            return e.getMessage().toString();
	        }
		
	    return accessToken;
	    }
	
}